@MMIv8_Ktype.Core_HostAddress = https://localhost:44304


POST {{MMIv8_Ktype.Core_HostAddress}}/MatchMakeModel/GetByModels
Content-Type: application/json
{
  "tD_SourceEntityModelHash": "003DEB088C04048C9C765F40BDF4EB28050703D366606640F7368FE93F10B7EC", 
  "mmI_SourceEntityModelHash": "639FFB977658CC53FC74E18E5C94983B9B973EBEDDAE3B545A8F453756091CCA"
}

###

GET {{MMIv8_Ktype.Core_HostAddress}}/Version

###

@VersionNumber=3
PATCH {{MMIv8_Ktype.Core_HostAddress}}/Version/{{VersionNumber}}?TecDocEntityVersion=2001_01

###

@MatchBaseType=Drive
GET {{MMIv8_Ktype.Core_HostAddress}}/MatchBase/GetByType/{{MatchBaseType}}

###

@Page=1
@PageSize=2
GET {{MMIv8_Ktype.Core_HostAddress}}/MatchEntity/GetAll?Page={{Page}}&PageSize={{PageSize}}

###

GET {{MMIv8_Ktype.Core_HostAddress}}/MatchEntity/MatchRefine

###
