<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MongoDB.Driver" />
		<PackageReference Include="Swashbuckle.AspNetCore" />
	</ItemGroup>

  <ItemGroup>
    <Folder Include="Logs\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MMIv8_Ktype.Api\MMIv8_Ktype.Api.csproj" />
    <ProjectReference Include="..\MMIv8_Ktype.Models\MMIv8_Ktype.Models.csproj" />
  </ItemGroup>

</Project>
