<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Refit.HttpClientFactory" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MMIv8_Ktype.AccessMdb\MMIv8_Ktype.AccessMdb.csproj" />
    <ProjectReference Include="..\MMIv8_Ktype.CSV\MMIv8_Ktype.CSV.csproj" />
    <ProjectReference Include="..\MMIv8_Ktype.Models\MMIv8_Ktype.Models.csproj" />
  </ItemGroup>

</Project>
