<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MMIv8_Ktype.AccessMdb\MMIv8_Ktype.AccessMdb.csproj" />
    <ProjectReference Include="..\MMIv8_Ktype.CSV\MMIv8_Ktype.CSV.csproj" />
    <ProjectReference Include="..\MMIv8_Ktype.Models\MMIv8_Ktype.Models.csproj" />
  </ItemGroup>

</Project>
